### ISSUE TITLE
Pager totals misspelled

### ISSUE THREAD

**Issue by ovikariy** [Grace951/react-table#2]
"Page 1 of totlas X, totlas Y rows" has the word "totals" misspelled. 
![image](https://user-images.githubusercontent.com/40619619/41951682-ad3c7aac-79fe-11e8-8205-100b0ed1e662.png)

**Comment by ovikariy** [comment]
In SortableTblPager.js line #86

**Comment by Grace951** [comment]
fix on v0.1.3, thanks
