### ISSUE TITLE
"PropTypes" issue

### ISSUE THREAD

**Issue by SoGCuicui** [Grace951/react-table#3]
Hi,

Reporting a warning message I have when I use your package:
"Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs"

I hope this may not be difficult to fix! :)

**Comment by Grace951** [comment]
Fixed on 1.1.1
